// token
export const GET_TOKEN_INFO_SUCCESS = "GET_TOKEN_INFO_SUCCESS";
export const TOKEN_UPDATE_SUCCESS = "TOKEN_UPDATE_SUCCESS";
export const TOKEN_UPDATE_FAIL = "TOKEN_UPDATE_FAIL";

// sale
export const GET_SALE_INFO_SUCCESS = "GET_SALE_INFO_SUCCESS";
export const SALE_UPDATE_SUCCESS = "SALE_UPDATE_SUCCESS";
export const SALE_UPDATE_FAIL = "SALE_UPDATE_FAIL";

// multisig contract
export const GET_MULTISIG_INFO_SUCCESS = "GET_MULTISIG_INFO_SUCCESS";
export const GET_MULTISIG_INFO_FAIL = "GET_MULTISIG_INFO_FAIL";
export const SUBMIT_TRANSACTION_SUCCESS = "SUBMIT_TRANSACTION_SUCCESS";
export const SUBMIT_TRANSACTION_FAIL = "SUBMIT_TRANSACTION_FAIL";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAIL = "UPDATE_TRANSACTION_FAIL";

// block status
export const BLOCK_PENDING = "BLOCK_PENDING";
export const BLOCK_CONFIRMED = "BLOCK_CONFIRMED";
